#!/bin/bash
# ============================================================
# ABCare OmniFlow — Local DNS Setup
# Runs on the UBUNTU SERVER (the clinic server PC)
#
# What this does:
#   1. Installs dnsmasq (lightweight LAN DNS server)
#   2. Maps clinic.local → this server's LAN IP
#   3. Configures dnsmasq to start on boot
#   4. Prints instructions for each client device
#
# Usage: sudo bash setup-local-dns.sh
# ============================================================

set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
info() { echo -e "${CYAN}[→]${NC} $1"; }

# ── Must run as root ──────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  err "Run as root: sudo bash setup-local-dns.sh"
fi

echo ""
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${CYAN}   ABCare OmniFlow — Local DNS Setup${NC}"
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── Detect this server's LAN IP ──────────────────────────────────────────
SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1)
if [ -z "$SERVER_IP" ]; then
  # Fallback: grab first non-loopback inet address
  SERVER_IP=$(ip -4 addr show scope global | grep -oP '(?<=inet )\d+\.\d+\.\d+\.\d+' | head -1)
fi
if [ -z "$SERVER_IP" ]; then
  err "Could not detect server LAN IP. Check: ip a"
fi

info "Detected server LAN IP: ${BOLD}$SERVER_IP${NC}"
echo ""

# ── Prompt for hostname ───────────────────────────────────────────────────
read -p "  Local hostname to use [clinic.local]: " CLINIC_HOST
CLINIC_HOST="${CLINIC_HOST:-clinic.local}"

# Strip port if accidentally included
CLINIC_HOST="${CLINIC_HOST%%:*}"

# ── Prompt for port (default 3000) ───────────────────────────────────────
read -p "  App port [3000]: " APP_PORT
APP_PORT="${APP_PORT:-3000}"

echo ""
info "Will map: ${BOLD}${CLINIC_HOST}${NC} → ${BOLD}${SERVER_IP}${NC}"
info "Staff will open: ${BOLD}http://${CLINIC_HOST}:${APP_PORT}${NC}"
echo ""

# ── Step 1: Install dnsmasq ───────────────────────────────────────────────
info "Step 1/4 — Installing dnsmasq..."

# Disable systemd-resolved stub listener (conflicts with dnsmasq on port 53)
if systemctl is-active systemd-resolved &>/dev/null; then
  # Tell resolved not to bind to port 53
  mkdir -p /etc/systemd/resolved.conf.d
  cat > /etc/systemd/resolved.conf.d/nodns.conf << 'EOF'
[Resolve]
DNSStubListener=no
EOF
  systemctl restart systemd-resolved
  log "systemd-resolved stub listener disabled"
fi

apt-get update -qq
apt-get install -y -qq dnsmasq
log "dnsmasq installed"

# ── Step 2: Configure dnsmasq ─────────────────────────────────────────────
info "Step 2/4 — Configuring dnsmasq..."

# Backup existing config
[ -f /etc/dnsmasq.conf ] && cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak

cat > /etc/dnsmasq.conf << EOF
# ABCare OmniFlow — Local DNS Configuration
# Generated by setup-local-dns.sh on $(date)

# Only listen on LAN interface (not loopback)
# dnsmasq will auto-detect the right interface
bind-interfaces

# Local domain — .local queries resolved here, everything else forwarded
local=/${CLINIC_HOST%%.*}.local/
domain=${CLINIC_HOST%%.*}.local

# Map clinic.local to this server
address=/${CLINIC_HOST}/${SERVER_IP}

# Also map bare hostname without .local
address=$(echo "/${CLINIC_HOST%%.*}/${SERVER_IP}")

# Forward all other DNS to upstream (Google + Cloudflare)
server=8.8.8.8
server=1.1.1.1

# Cache 1000 entries — speeds up repeat lookups
cache-size=1000

# Log queries to syslog for debugging
log-queries
log-facility=/var/log/dnsmasq.log
EOF

log "dnsmasq configured"

# ── Step 3: Enable and start dnsmasq ──────────────────────────────────────
info "Step 3/4 — Starting dnsmasq..."
systemctl enable dnsmasq
systemctl restart dnsmasq
sleep 1

if systemctl is-active --quiet dnsmasq; then
  log "dnsmasq is running"
else
  err "dnsmasq failed to start. Check: journalctl -xeu dnsmasq"
fi

# ── Step 4: Add server's own /etc/hosts entry ─────────────────────────────
info "Step 4/4 — Adding local /etc/hosts entry..."

# Remove any existing entry for this hostname
sed -i "/${CLINIC_HOST}/d" /etc/hosts
echo "${SERVER_IP}  ${CLINIC_HOST}" >> /etc/hosts
log "/etc/hosts updated"

# ── Verify DNS resolution works from the server itself ────────────────────
echo ""
info "Verifying DNS resolution..."
if nslookup "${CLINIC_HOST}" 127.0.0.1 &>/dev/null 2>&1; then
  RESOLVED=$(nslookup "${CLINIC_HOST}" 127.0.0.1 2>/dev/null | grep 'Address' | tail -1 | awk '{print $2}')
  log "${CLINIC_HOST} resolves to: ${RESOLVED}"
else
  # dig fallback
  if command -v dig &>/dev/null; then
    RESOLVED=$(dig @127.0.0.1 "${CLINIC_HOST}" +short 2>/dev/null | head -1)
    [ -n "$RESOLVED" ] && log "${CLINIC_HOST} resolves to: ${RESOLVED}" || warn "DNS test inconclusive — dnsmasq may need 30 seconds to fully start"
  else
    warn "nslookup not found — install with: apt install dnsutils"
  fi
fi

# ── Print client setup instructions ───────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}   ✓  Local DNS Setup Complete!${NC}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "   ${BOLD}Server IP:${NC}        ${SERVER_IP}"
echo -e "   ${BOLD}Hostname:${NC}         ${CLINIC_HOST}"
echo -e "   ${BOLD}App URL:${NC}          http://${CLINIC_HOST}:${APP_PORT}"
echo ""
echo -e "${BOLD}━━━ HOW TO CONNECT CLIENT DEVICES ━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}Option A — Point each PC's DNS to this server (best):${NC}"
echo "  On each clinic PC, set the DNS server address to: ${SERVER_IP}"
echo ""
echo "  Windows 7/10:"
echo "   Control Panel → Network → Change adapter settings"
echo "   → Properties → IPv4 → Use following DNS: ${SERVER_IP}"
echo ""
echo "  Windows 11:"
echo "   Settings → Network → Ethernet → Edit DNS"
echo "   → Manual → IPv4 DNS: ${SERVER_IP}"
echo ""
echo "  Ubuntu/Linux:"
echo "   sudo nano /etc/resolv.conf"
echo "   Add: nameserver ${SERVER_IP}"
echo ""
echo -e "${BOLD}Option B — Add to each PC's hosts file (no DNS needed):${NC}"
echo "  On each clinic PC, add this line to the hosts file:"
echo "  ${SERVER_IP}  ${CLINIC_HOST}"
echo ""
echo "  Windows hosts file: C:\\Windows\\System32\\drivers\\etc\\hosts"
echo "  Linux hosts file:   /etc/hosts"
echo ""
echo -e "${BOLD}Option C — Configure your router's DNS (covers all devices):${NC}"
echo "  Log into your router admin panel (usually 192.168.1.1)"
echo "  Find DNS settings → set Primary DNS to: ${SERVER_IP}"
echo "  All devices on the network will automatically use this DNS"
echo ""
echo -e "${BOLD}━━━ AFTER SETTING UP CLIENT DNS ━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Staff open browser and type:"
echo -e "  ${BOLD}http://${CLINIC_HOST}:${APP_PORT}${NC}"
echo ""
echo "  That's it. No IP address to remember."
echo ""
echo -e "${BOLD}━━━ MANAGEMENT COMMANDS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Check dnsmasq status:   sudo systemctl status dnsmasq"
echo "  View DNS query log:     sudo tail -f /var/log/dnsmasq.log"
echo "  Restart dnsmasq:        sudo systemctl restart dnsmasq"
echo "  Test resolution:        nslookup ${CLINIC_HOST} ${SERVER_IP}"
echo ""
